Try to debug strange YAML related CI error
    ERROR:  While executing gem ... (ArgumentError)
      undefined class/module YAML::

Happening since 58adb1636be32fb95173f01e448673dbae4511b0