Optimize dynamic string interpolation for symbol/true/false/nil/0-9
This provides a significant speedup for symbol, true, false,
nil, and 0-9, and a small speedup in most other cases.

Speedups (using included benchmarks):
:symbol        :: 60%
0-9            :: 50%
nil/true/false :: 20%
integer        :: 10%
[]             :: 10%
""             :: 3%

One reason this approach is faster is it can significantly reduce
the number of VM instructions for each interpolated value:

Before:

```
0005 dup
0006 checktype                              T_STRING
0008 branchif                               14
0010 dup
0011 opt_send_without_block                 <calldata!mid:to_s, argc:0, FCALL|ARGS_SIMPLE>
0013 tostring
```

After:

```
0005 tostring                               <calldata!mid:to_s, argc:0, ARGS_SIMPLE>
```

Initial idea, approach, and benchmarks from Eric Wong. I applied
the same approach against the master branch, updating it to handle
the significant internal changes since this was first proposed 4
years ago (such as CALL_INFO/CALL_CACHE -> CALL_DATA). I also
expanded it to optimize true/false/nil/0-9, and added handling of
missing methods, refined methods, and RUBY_DEBUG.

This requires making a few functions non-static, and adding some
non-static functions. rb_vm_call0_body is added as a non-static
function to appease Visual Studio 2019, fixing this error:

```
../src/vm.c(4167): error C2129: static function 'VALUE vm_call0_body(rb_execution_context_t *,rb_calling_info *,const VALUE *)' declared but not defined
```

The YJIT support for optimizing the tostring instruction is
disabled by this until YJIT is updated for the new tostring
instruction. This also disables 4 YJIT tests to fix the following
failures due to disabling the tostring instruction optimization:

```
Expected no exits, but got
{:tostring=>1}
```

Implements [Feature #13715]

Co-authored-by: Eric Wong <e@80x24.org>